### ISSUE TITLE
Error: java.lang.NoSuchMethodError: no static or non-static method "JNIHandler;.getProdUrl

### ISSUE THREAD

**Issue by harry-sm** [Shahin-Sefidgaran/seon-flutter-sdk#8]
Hello @Shahin-Sefidgaran, 

Thank you for creating this Flutter SDK.

Unfortunately, when the method `SeonPlugin().getFingerPrintBase64()` is called an error is thrown.

Thank you for addressing this issue.

```
E/AndroidRuntime(13581): Process: com.mba.giftme, PID: 13581
E/AndroidRuntime(13581): java.lang.NoSuchMethodError: no static or non-static method "Lio/seon/androidsdk/service/JNIHandler;.getProdUrl(Ljava/lang/Object;)Ljava/lang/String;"
E/AndroidRuntime(13581):        at java.lang.Runtime.nativeLoad(Native Method)
E/AndroidRuntime(13581):        at java.lang.Runtime.nativeLoad(Runtime.java:1121)
E/AndroidRuntime(13581):        at java.lang.Runtime.loadLibrary0(Runtime.java:1075)
E/AndroidRuntime(13581):        at java.lang.Runtime.loadLibrary0(Runtime.java:998)
E/AndroidRuntime(13581):        at java.lang.System.loadLibrary(System.java:1656)
E/AndroidRuntime(13581):        at g1.e.b(SystemLibraryLoader.java:1)
E/AndroidRuntime(13581):        at g1.d.g(ReLinkerInstance.java:3)
E/AndroidRuntime(13581):        at g1.d.f(ReLinkerInstance.java:3)
E/AndroidRuntime(13581):        at g1.c.b(ReLinker.java:1)
E/AndroidRuntime(13581):        at g1.c.a(ReLinker.java:1)
E/AndroidRuntime(13581):        at io.seon.androidsdk.service.JNIHandler.a(Unknown Source:6)
E/AndroidRuntime(13581):        at io.seon.androidsdk.service.d4.<init>(Unknown Source:14)
E/AndroidRuntime(13581):        at io.seon.androidsdk.service.h4.<init>(Unknown Source:9)
E/AndroidRuntime(13581):        at io.seon.androidsdk.service.c4.a(Unknown Source:27)
E/AndroidRuntime(13581):        at d1.b.b(SeonPlugin.kt:2)
E/AndroidRuntime(13581):        at d1.b.onMethodCall(SeonPlugin.kt:5)
E/AndroidRuntime(13581):        at lb.j$a.a(MethodChannel.java:2)
E/AndroidRuntime(13581):        at ya.c.l(DartMessenger.java:2)
E/AndroidRuntime(13581):        at ya.c.m(DartMessenger.java:3)
E/AndroidRuntime(13581):        at ya.c.i(Unknown Source:0)
E/AndroidRuntime(13581):        at ya.b.run(Unknown Source:12)
E/AndroidRuntime(13581):        at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(13581):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(13581):        at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(13581):        at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(13581):        at android.app.ActivityThread.main(ActivityThread.java:8663)
E/AndroidRuntime(13581):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13581):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
E/AndroidRuntime(13581):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by SaowaluckT** [comment]
I had the same issue.

>  Flutter (Channel stable, 3.16.3, on macOS 14.2.1 23C71 darwin-arm64, locale en-TH)
    • Flutter version 3.16.3 on channel stable
    • Dart version 3.2.3

**Comment by harry-sm** [comment]
@SaowaluckT seems like there is a similar issue for Seon Android SDK v6

**Comment by Shahin-Sefidgaran** [comment]
Hello @harry-sm @SaowaluckT 
Thanks for opening this issue, as @harry-sm have also said this issue needs to be fixed from Seon Android SDK
however for an alternative fix you can add:
```
-keep class io.seon.androidsdk.service.JNIHandler {
    <methods>;
}
```
to the following file for your flutter project
`android\app\proguard-rules.pro`
please let me know if there is anymore issue.

**Comment by harry-sm** [comment]
Hello @Shahin-Sefidgaran Thanks a lot! It works now.
